### ISSUE TITLE
Could not pass event PlayerInteractEvent to TradingShops v2.1.1

### ISSUE THREAD

**Issue by davidolos** [chistian95/TradingShops#8]
Hi there, plugin works pretty fine on my server, but my server console is spammed by this.  Thanks for support. 

[20:23:05 ERROR]: Could not pass event PlayerInteractEvent to TradingShops v2.1.1
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:222) ~[?:?]
        at es.elzoo.tradingshops.EventShop.onPlayerInteractStock(EventShop.java:34) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-174]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-174]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-174]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-174]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:457) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-174]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by chistian95** [comment]
Looks like you have an invalid block id set for the stock block. Check your config file for the stock block id. If you don't see anything wrong, please send me your config file to check it up ;)

**Comment by chistian95** [comment]
There is no way to do it right now. But try to set the stock block as air (?) maybe it works that way. If it does not work, tell me to make a quick patch to add an option to disable stock blocks ;)
